package Model;
// Generated 27-04-2016 11:18:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta  implements java.io.Serializable {


     private BigDecimal idCuenta;
     private Cliente cliente;
     private Clob descripcion;
     private BigDecimal saldo;
     private BigDecimal activa;
     private Date fechaCaducacion;

    public Cuenta() {
    }

	
    public Cuenta(BigDecimal idCuenta, Cliente cliente, BigDecimal saldo) {
        this.idCuenta = idCuenta;
        this.cliente = cliente;
        this.saldo = saldo;
    }
    public Cuenta(BigDecimal idCuenta, Cliente cliente, Clob descripcion, BigDecimal saldo, BigDecimal activa, Date fechaCaducacion) {
       this.idCuenta = idCuenta;
       this.cliente = cliente;
       this.descripcion = descripcion;
       this.saldo = saldo;
       this.activa = activa;
       this.fechaCaducacion = fechaCaducacion;
    }
   
    public BigDecimal getIdCuenta() {
        return this.idCuenta;
    }
    
    public void setIdCuenta(BigDecimal idCuenta) {
        this.idCuenta = idCuenta;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Clob getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(Clob descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }
    public BigDecimal getActiva() {
        return this.activa;
    }
    
    public void setActiva(BigDecimal activa) {
        this.activa = activa;
    }
    public Date getFechaCaducacion() {
        return this.fechaCaducacion;
    }
    
    public void setFechaCaducacion(Date fechaCaducacion) {
        this.fechaCaducacion = fechaCaducacion;
    }




}


