package Model;
// Generated 27-04-2016 11:18:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Despacho generated by hbm2java
 */
public class Despacho  implements java.io.Serializable {


     private BigDecimal idDespacho;
     private Pedido pedido;
     private Repartidor repartidor;
     private Venta venta;
     private String direccion;
     private String comuna;
     private BigDecimal numeracion;
     private Set ventas = new HashSet(0);

    public Despacho() {
    }

	
    public Despacho(BigDecimal idDespacho, Pedido pedido, Repartidor repartidor, String direccion, String comuna) {
        this.idDespacho = idDespacho;
        this.pedido = pedido;
        this.repartidor = repartidor;
        this.direccion = direccion;
        this.comuna = comuna;
    }
    public Despacho(BigDecimal idDespacho, Pedido pedido, Repartidor repartidor, Venta venta, String direccion, String comuna, BigDecimal numeracion, Set ventas) {
       this.idDespacho = idDespacho;
       this.pedido = pedido;
       this.repartidor = repartidor;
       this.venta = venta;
       this.direccion = direccion;
       this.comuna = comuna;
       this.numeracion = numeracion;
       this.ventas = ventas;
    }
   
    public BigDecimal getIdDespacho() {
        return this.idDespacho;
    }
    
    public void setIdDespacho(BigDecimal idDespacho) {
        this.idDespacho = idDespacho;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Repartidor getRepartidor() {
        return this.repartidor;
    }
    
    public void setRepartidor(Repartidor repartidor) {
        this.repartidor = repartidor;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getComuna() {
        return this.comuna;
    }
    
    public void setComuna(String comuna) {
        this.comuna = comuna;
    }
    public BigDecimal getNumeracion() {
        return this.numeracion;
    }
    
    public void setNumeracion(BigDecimal numeracion) {
        this.numeracion = numeracion;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


