package Model;
// Generated 27-04-2016 11:18:03 by Hibernate Tools 4.3.1



/**
 * Ingrediente generated by hbm2java
 */
public class Ingrediente  implements java.io.Serializable {


     private String idIngrediente;
     private Plato plato;
     private String nombre;

    public Ingrediente() {
    }

    public Ingrediente(String idIngrediente, Plato plato, String nombre) {
       this.idIngrediente = idIngrediente;
       this.plato = plato;
       this.nombre = nombre;
    }
   
    public String getIdIngrediente() {
        return this.idIngrediente;
    }
    
    public void setIdIngrediente(String idIngrediente) {
        this.idIngrediente = idIngrediente;
    }
    public Plato getPlato() {
        return this.plato;
    }
    
    public void setPlato(Plato plato) {
        this.plato = plato;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


