package Model;
// Generated 27-04-2016 11:18:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private BigDecimal rut;
     private String dv;
     private String nombre;
     private String app;
     private String apm;
     private String direccion;
     private BigDecimal telefono;
     private Set clientes = new HashSet(0);
     private Set usuarios = new HashSet(0);
     private Set repartidors = new HashSet(0);

    public Persona() {
    }

	
    public Persona(BigDecimal rut, String dv, String nombre, String app, String apm) {
        this.rut = rut;
        this.dv = dv;
        this.nombre = nombre;
        this.app = app;
        this.apm = apm;
    }
    public Persona(BigDecimal rut, String dv, String nombre, String app, String apm, String direccion, BigDecimal telefono, Set clientes, Set usuarios, Set repartidors) {
       this.rut = rut;
       this.dv = dv;
       this.nombre = nombre;
       this.app = app;
       this.apm = apm;
       this.direccion = direccion;
       this.telefono = telefono;
       this.clientes = clientes;
       this.usuarios = usuarios;
       this.repartidors = repartidors;
    }
   
    public BigDecimal getRut() {
        return this.rut;
    }
    
    public void setRut(BigDecimal rut) {
        this.rut = rut;
    }
    public String getDv() {
        return this.dv;
    }
    
    public void setDv(String dv) {
        this.dv = dv;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApp() {
        return this.app;
    }
    
    public void setApp(String app) {
        this.app = app;
    }
    public String getApm() {
        return this.apm;
    }
    
    public void setApm(String apm) {
        this.apm = apm;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public BigDecimal getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(BigDecimal telefono) {
        this.telefono = telefono;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getRepartidors() {
        return this.repartidors;
    }
    
    public void setRepartidors(Set repartidors) {
        this.repartidors = repartidors;
    }




}


