package Model;
// Generated 27-04-2016 11:18:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Plato generated by hbm2java
 */
public class Plato  implements java.io.Serializable {


     private BigDecimal idPlato;
     private Categoria categoria;
     private Proveedor proveedor;
     private String nombre;
     private String descripcion;
     private BigDecimal precio;
     private String tipoPlato;
     private Set imagens = new HashSet(0);
     private Set ingredientes = new HashSet(0);
     private Set menuClientes = new HashSet(0);
     private Set pedidos = new HashSet(0);

    public Plato() {
    }

	
    public Plato(BigDecimal idPlato, Categoria categoria, String nombre, BigDecimal precio) {
        this.idPlato = idPlato;
        this.categoria = categoria;
        this.nombre = nombre;
        this.precio = precio;
    }
    public Plato(BigDecimal idPlato, Categoria categoria, Proveedor proveedor, String nombre, String descripcion, BigDecimal precio, String tipoPlato, Set imagens, Set ingredientes, Set menuClientes, Set pedidos) {
       this.idPlato = idPlato;
       this.categoria = categoria;
       this.proveedor = proveedor;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precio = precio;
       this.tipoPlato = tipoPlato;
       this.imagens = imagens;
       this.ingredientes = ingredientes;
       this.menuClientes = menuClientes;
       this.pedidos = pedidos;
    }
   
    public BigDecimal getIdPlato() {
        return this.idPlato;
    }
    
    public void setIdPlato(BigDecimal idPlato) {
        this.idPlato = idPlato;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public String getTipoPlato() {
        return this.tipoPlato;
    }
    
    public void setTipoPlato(String tipoPlato) {
        this.tipoPlato = tipoPlato;
    }
    public Set getImagens() {
        return this.imagens;
    }
    
    public void setImagens(Set imagens) {
        this.imagens = imagens;
    }
    public Set getIngredientes() {
        return this.ingredientes;
    }
    
    public void setIngredientes(Set ingredientes) {
        this.ingredientes = ingredientes;
    }
    public Set getMenuClientes() {
        return this.menuClientes;
    }
    
    public void setMenuClientes(Set menuClientes) {
        this.menuClientes = menuClientes;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


