package Model;
// Generated 27-04-2016 11:18:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private BigDecimal idUsuario;
     private Persona persona;
     private TipoUsuario tipoUsuario;
     private String nombreUsuario;
     private String contrasena;

    public Usuario() {
    }

    public Usuario(BigDecimal idUsuario, Persona persona, TipoUsuario tipoUsuario, String nombreUsuario, String contrasena) {
       this.idUsuario = idUsuario;
       this.persona = persona;
       this.tipoUsuario = tipoUsuario;
       this.nombreUsuario = nombreUsuario;
       this.contrasena = contrasena;
    }
   
    public BigDecimal getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(BigDecimal idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }




}


