package proyecto.tablas;
// Generated 27-04-2016 11:18:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private BigDecimal idCliente;
     private Empresa empresa;
     private Persona persona;
     private String tipoCliente;
     private Set estadoPedidos = new HashSet(0);
     private Set pedidos = new HashSet(0);
     private Set menuClientes = new HashSet(0);
     private Set cuentas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(BigDecimal idCliente, Persona persona) {
        this.idCliente = idCliente;
        this.persona = persona;
    }
    public Cliente(BigDecimal idCliente, Empresa empresa, Persona persona, String tipoCliente, Set estadoPedidos, Set pedidos, Set menuClientes, Set cuentas) {
       this.idCliente = idCliente;
       this.empresa = empresa;
       this.persona = persona;
       this.tipoCliente = tipoCliente;
       this.estadoPedidos = estadoPedidos;
       this.pedidos = pedidos;
       this.menuClientes = menuClientes;
       this.cuentas = cuentas;
    }
   
    public BigDecimal getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(BigDecimal idCliente) {
        this.idCliente = idCliente;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getTipoCliente() {
        return this.tipoCliente;
    }
    
    public void setTipoCliente(String tipoCliente) {
        this.tipoCliente = tipoCliente;
    }
    public Set getEstadoPedidos() {
        return this.estadoPedidos;
    }
    
    public void setEstadoPedidos(Set estadoPedidos) {
        this.estadoPedidos = estadoPedidos;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }
    public Set getMenuClientes() {
        return this.menuClientes;
    }
    
    public void setMenuClientes(Set menuClientes) {
        this.menuClientes = menuClientes;
    }
    public Set getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set cuentas) {
        this.cuentas = cuentas;
    }




}


