package proyecto.tablas;
// Generated 27-04-2016 11:18:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Clob;

/**
 * EstadoPedido generated by hbm2java
 */
public class EstadoPedido  implements java.io.Serializable {


     private BigDecimal idEstadoPedido;
     private Cliente cliente;
     private BigDecimal tiempoEntrega;
     private Clob descripcion;

    public EstadoPedido() {
    }

	
    public EstadoPedido(BigDecimal idEstadoPedido, Cliente cliente, BigDecimal tiempoEntrega) {
        this.idEstadoPedido = idEstadoPedido;
        this.cliente = cliente;
        this.tiempoEntrega = tiempoEntrega;
    }
    public EstadoPedido(BigDecimal idEstadoPedido, Cliente cliente, BigDecimal tiempoEntrega, Clob descripcion) {
       this.idEstadoPedido = idEstadoPedido;
       this.cliente = cliente;
       this.tiempoEntrega = tiempoEntrega;
       this.descripcion = descripcion;
    }
   
    public BigDecimal getIdEstadoPedido() {
        return this.idEstadoPedido;
    }
    
    public void setIdEstadoPedido(BigDecimal idEstadoPedido) {
        this.idEstadoPedido = idEstadoPedido;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public BigDecimal getTiempoEntrega() {
        return this.tiempoEntrega;
    }
    
    public void setTiempoEntrega(BigDecimal tiempoEntrega) {
        this.tiempoEntrega = tiempoEntrega;
    }
    public Clob getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(Clob descripcion) {
        this.descripcion = descripcion;
    }




}


