package proyecto.tablas;
// Generated 27-04-2016 11:18:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Clob;

/**
 * Imagen generated by hbm2java
 */
public class Imagen  implements java.io.Serializable {


     private BigDecimal idImagen;
     private Plato plato;
     private Clob nombre;
     private Clob tipo;
     private BigDecimal peso;
     private Clob ruta;

    public Imagen() {
    }

	
    public Imagen(BigDecimal idImagen, Plato plato) {
        this.idImagen = idImagen;
        this.plato = plato;
    }
    public Imagen(BigDecimal idImagen, Plato plato, Clob nombre, Clob tipo, BigDecimal peso, Clob ruta) {
       this.idImagen = idImagen;
       this.plato = plato;
       this.nombre = nombre;
       this.tipo = tipo;
       this.peso = peso;
       this.ruta = ruta;
    }
   
    public BigDecimal getIdImagen() {
        return this.idImagen;
    }
    
    public void setIdImagen(BigDecimal idImagen) {
        this.idImagen = idImagen;
    }
    public Plato getPlato() {
        return this.plato;
    }
    
    public void setPlato(Plato plato) {
        this.plato = plato;
    }
    public Clob getNombre() {
        return this.nombre;
    }
    
    public void setNombre(Clob nombre) {
        this.nombre = nombre;
    }
    public Clob getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Clob tipo) {
        this.tipo = tipo;
    }
    public BigDecimal getPeso() {
        return this.peso;
    }
    
    public void setPeso(BigDecimal peso) {
        this.peso = peso;
    }
    public Clob getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Clob ruta) {
        this.ruta = ruta;
    }




}


