package proyecto.tablas;
// Generated 27-04-2016 11:18:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Repartidor generated by hbm2java
 */
public class Repartidor  implements java.io.Serializable {


     private BigDecimal idRepartidor;
     private Persona persona;
     private String vehiculo;
     private String licencia;
     private Set despachos = new HashSet(0);

    public Repartidor() {
    }

	
    public Repartidor(BigDecimal idRepartidor, Persona persona, String vehiculo) {
        this.idRepartidor = idRepartidor;
        this.persona = persona;
        this.vehiculo = vehiculo;
    }
    public Repartidor(BigDecimal idRepartidor, Persona persona, String vehiculo, String licencia, Set despachos) {
       this.idRepartidor = idRepartidor;
       this.persona = persona;
       this.vehiculo = vehiculo;
       this.licencia = licencia;
       this.despachos = despachos;
    }
   
    public BigDecimal getIdRepartidor() {
        return this.idRepartidor;
    }
    
    public void setIdRepartidor(BigDecimal idRepartidor) {
        this.idRepartidor = idRepartidor;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(String vehiculo) {
        this.vehiculo = vehiculo;
    }
    public String getLicencia() {
        return this.licencia;
    }
    
    public void setLicencia(String licencia) {
        this.licencia = licencia;
    }
    public Set getDespachos() {
        return this.despachos;
    }
    
    public void setDespachos(Set despachos) {
        this.despachos = despachos;
    }




}


