package proyecto.tablas;
// Generated 27-04-2016 11:18:03 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoPedido generated by hbm2java
 */
public class TipoPedido  implements java.io.Serializable {


     private BigDecimal idTipoPedido;
     private String nombre;
     private Set pedidos = new HashSet(0);

    public TipoPedido() {
    }

	
    public TipoPedido(BigDecimal idTipoPedido, String nombre) {
        this.idTipoPedido = idTipoPedido;
        this.nombre = nombre;
    }
    public TipoPedido(BigDecimal idTipoPedido, String nombre, Set pedidos) {
       this.idTipoPedido = idTipoPedido;
       this.nombre = nombre;
       this.pedidos = pedidos;
    }
   
    public BigDecimal getIdTipoPedido() {
        return this.idTipoPedido;
    }
    
    public void setIdTipoPedido(BigDecimal idTipoPedido) {
        this.idTipoPedido = idTipoPedido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


